# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-12 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
