# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-17 19:02
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsuccessfulEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activation_email', models.BooleanField(default=False)),
                ('is_forgot_password_email', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('message', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reattempt_on', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, related_name='unsuccessful_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnsuccessfulSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=512)),
                ('phone_numbers', models.TextField(validators=[django.core.validators.RegexValidator('^([7-9]\\d{9}(,[7-9]\\d{9})*)$')])),
                ('sender', models.CharField(default='GGSIPU', max_length=6)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reattempt_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
