# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170618_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSDeliveryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('recipients', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('session_id', models.CharField(max_length=128)),
                ('status_desc', models.CharField(blank=True, max_length=512)),
                ('error_desc', models.CharField(blank=True, max_length=512)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
