# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-17 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0002_auto_20170613_2043'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0015_auto_20170613_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('V', 'Verification'), ('P', 'Placement'), ('G', 'General')], default=None, max_length=1, verbose_name='Issue Type')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('message', models.CharField(max_length=4096, verbose_name='Message')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('marked', models.BooleanField(default=False, verbose_name='Marked Important')),
                ('solved_by', models.CharField(blank=True, max_length=64, verbose_name='Answered By')),
                ('solver_username', models.CharField(blank=True, max_length=32, verbose_name='Solver')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='student.Student')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='college.College')),
            ],
        ),
        migrations.CreateModel(
            name='IssueReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=4096, verbose_name='Reply')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('root_issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reply', to='notification.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Seen?')),
                ('message', models.CharField(blank=True, max_length=128, verbose_name='Message')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_actor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=4096, verbose_name='Message')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('sms_message', models.CharField(blank=True, max_length=128, null=True, verbose_name='SMS Message')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FDBK', 'Feedback'), ('RQFR', 'Request Feature'), ('REBG', 'Report Bug')], default=None, max_length=4, verbose_name='Report Type')),
                ('message', models.CharField(max_length=4096, verbose_name='Message')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_data', to='notification.NotificationData'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_target', to=settings.AUTH_USER_MODEL),
        ),
    ]
