# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20160831_0903'),
        ('faculty', '0002_auto_20160811_0204'),
        ('college', '0001_initial'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('V', 'Verification'), ('P', 'Placement'), ('G', 'General')], default=None, max_length=1, verbose_name='Issue Type')),
                ('subject', models.CharField(max_length=32, verbose_name='Subject')),
                ('message', models.CharField(max_length=2046, verbose_name='Message')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('marked', models.BooleanField(default=False, verbose_name='Marked Important')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='student.Student')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='college.College')),
                ('solved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='faculty.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='IssueReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=2046, verbose_name='Reply')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reply', to='faculty.Faculty')),
                ('root_issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reply', to='notification.Issue')),
            ],
        ),
    ]
