# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=512, verbose_name='Message'),
        ),
    ]
