# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20170622_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('FDBK', 'Feedback'), ('RQFR', 'Request Feature'), ('REBG', 'Report Bug'), ('CTAM', 'Contact Admin')], default=None, max_length=4, verbose_name='Report Type'),
        ),
    ]
