# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-26 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20170623_0231'),
        ('notification', '0003_auto_20170626_0015'),
    ]

    operations = [
    ]
