# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0003_auto_20170209_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=4096, null=True, verbose_name='Message')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('sms_message', models.CharField(blank=True, max_length=128, verbose_name='SMS Message')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FDBK', 'Feedback'), ('RQFR', 'Request Feature'), ('REBG', 'Report Bug')], default=None, max_length=4, verbose_name='Report Type')),
                ('message', models.CharField(max_length=4096, verbose_name='Message')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AlterField(
            model_name='issue',
            name='message',
            field=models.CharField(max_length=4096, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='subject',
            field=models.CharField(max_length=256, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='issuereply',
            name='reply',
            field=models.CharField(max_length=4096, verbose_name='Reply'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_data', to='notification.NotificationData'),
        ),
    ]
