# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20170209_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='creation_time',
        ),
    ]
