# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('FDBK', 'Feedback'), ('RQFR', 'Request Feature'), ('REBG', 'Report Bug'), ('CTAM', 'Contact Admin')], default='REBG', max_length=4, verbose_name='Report Type'),
        ),
    ]
