# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_notification_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdata',
            name='sms_message',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SMS Message'),
        ),
    ]
