# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-09 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20170712_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdata',
            name='sms_message',
            field=models.CharField(blank=True, max_length=159, null=True, verbose_name='SMS Message'),
        ),
    ]
