# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-16 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20170210_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationdata',
            name='creation_time',
        ),
        migrations.AddField(
            model_name='notification',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 16, 21, 26, 21, 354488, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=128, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_data', to='notification.NotificationData'),
        ),
        migrations.AlterField(
            model_name='notificationdata',
            name='message',
            field=models.TextField(blank=True, max_length=4096, verbose_name='Message'),
        ),
    ]
