# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-24 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='college_alias',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='college_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='college_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='college',
            unique_together=set([('code', 'year')]),
        ),
    ]
