# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-24 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170624_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='alias',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
