# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-24 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20170624_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='total_students_selected',
            new_name='total_offers',
        ),
    ]
