# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissociation',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissociations', to='college.College'),
        ),
        migrations.AlterField(
            model_name='dissociation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissociations', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='dissociation',
            name='duration',
            field=models.DateField(blank=True, help_text='Choose the date till when you want to block this user from associating with you.', null=True),
        ),
        migrations.AlterField(
            model_name='placementsession',
            name='ended',
            field=models.BooleanField(default=False, help_text='Setting it to true would mean that the students currently in the session are selected.', verbose_name='Has the placement session has ended'),
        ),
        migrations.AlterField(
            model_name='placementsession',
            name='recent_deadline',
            field=models.DateField(help_text='Choose the deadline date for an event. Eg. Last date for applying. If no event is scheduled for now, choose an arbitrary date.', null=True, verbose_name='Deadline'),
        ),
    ]
