# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-12 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20160811_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='approved',
            field=models.NullBooleanField(default=None),
        ),
    ]
