# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 18:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20161006_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectioncriteria',
            name='doctorate',
            field=models.CharField(blank=True, choices=[('50', '50 and above'), ('60', '60 and above'), ('65', '65 and above'), ('70', '70 and above'), ('75', '75 and above'), ('80', '80 and above'), ('85', '85 and above')], max_length=2, verbose_name='Doctorate Percentage'),
        ),
        migrations.AlterField(
            model_name='selectioncriteria',
            name='graduation',
            field=models.CharField(blank=True, choices=[('50', '50 and above'), ('60', '60 and above'), ('65', '65 and above'), ('70', '70 and above'), ('75', '75 and above'), ('80', '80 and above'), ('85', '85 and above')], max_length=2, verbose_name='Graduation Percentage'),
        ),
        migrations.AlterField(
            model_name='selectioncriteria',
            name='post_graduation',
            field=models.CharField(blank=True, choices=[('50', '50 and above'), ('60', '60 and above'), ('65', '65 and above'), ('70', '70 and above'), ('75', '75 and above'), ('80', '80 and above'), ('85', '85 and above')], max_length=2, verbose_name='Post Graduation Percentage'),
        ),
        migrations.AlterField(
            model_name='selectioncriteria',
            name='tenth',
            field=models.CharField(blank=True, choices=[('50', '50 and above'), ('60', '60 and above'), ('65', '65 and above'), ('70', '70 and above'), ('75', '75 and above'), ('80', '80 and above'), ('85', '85 and above')], max_length=2, verbose_name='Xth Percentage'),
        ),
        migrations.AlterField(
            model_name='selectioncriteria',
            name='twelfth',
            field=models.CharField(blank=True, choices=[('50', '50 and above'), ('60', '60 and above'), ('65', '65 and above'), ('70', '70 and above'), ('75', '75 and above'), ('80', '80 and above'), ('85', '85 and above')], max_length=2, verbose_name='XIIth Percentage'),
        ),
        migrations.AlterField(
            model_name='selectioncriteria',
            name='years',
            field=models.CharField(blank=True, help_text='Eg. 1,2,3 (Without spaces anywhere)(In increasing order)', max_length=11, validators=[django.core.validators.RegexValidator('^([1-6](,[1-6])*)?$')], verbose_name='Which year students may apply'),
        ),
    ]
