# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 15:33
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_association_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salary to be offered in LPA.', max_digits=4, validators=django.core.validators.MinValueValidator(Decimal('0')), verbose_name='Salary (LPA)'),
        ),
        migrations.AddField(
            model_name='association',
            name='type',
            field=models.CharField(choices=[('I', 'Internship'), ('J', 'Job')], default='J', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='association',
            name='desc',
            field=models.TextField(blank=True, verbose_name="Placement details you'd want to mention"),
        ),
        migrations.AlterField(
            model_name='association',
            name='streams',
            field=models.ManyToManyField(help_text='Choose particular stream(s).', related_name='associations', to='college.Stream'),
        ),
    ]
