# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20161010_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectioncriteria',
            name='tenth',
            field=models.CharField(blank=True, choices=[('60', '60 and above'), ('70', '70 and above'), ('75', '75 and above'), ('80', '80 and above'), ('85', '85 and above'), ('90', '90 and above'), ('95', '95 and above')], max_length=2, verbose_name='Xth Percentage'),
        ),
        migrations.AlterField(
            model_name='selectioncriteria',
            name='twelfth',
            field=models.CharField(blank=True, choices=[('60', '60 and above'), ('70', '70 and above'), ('75', '75 and above'), ('80', '80 and above'), ('85', '85 and above'), ('90', '90 and above'), ('95', '95 and above')], max_length=2, verbose_name='XIIth Percentage'),
        ),
    ]
