# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20161012_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissociation',
            name='duration',
        ),
        migrations.AddField(
            model_name='dissociation',
            name='reason',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Reason(s)'),
        ),
        migrations.AddField(
            model_name='dissociation',
            name='when',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dissociation',
            name='initiator',
            field=models.CharField(choices=[('C', 'College'), ('CO', 'Company')], default='C', max_length=2, verbose_name='Who initiated it'),
        ),
    ]
