# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 00:21
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20160830_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Salary to be offered in LPA.', max_digits=4, validators=django.core.validators.MinValueValidator(Decimal('0')), verbose_name='Salary (Lakhs P.A.)'),
        ),
        migrations.AlterField(
            model_name='dissociation',
            name='duration',
            field=models.DateField(blank=True, help_text='Choose the date till when you want to block this user from contacting you.', null=True),
        ),
    ]
