# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20160831_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementsession',
            name='recent_deadline',
        ),
        migrations.AddField(
            model_name='placementsession',
            name='application_deadline',
            field=models.DateField(help_text='Choose the deadline date for an event. Eg. Last date for applying. If no event is scheduled for now, choose an arbitrary future date.', null=True, verbose_name='Application Deadline'),
        ),
    ]
