# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20170618_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dissociation',
            old_name='when',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='dissociation',
            name='reason',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Reasons'),
        ),
        migrations.AlterUniqueTogether(
            name='dissociation',
            unique_together=set([('company', 'college', 'initiator')]),
        ),
    ]
