# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_auto_20160904_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementsession',
            name='last_modified_by',
            field=models.CharField(choices=[('C', 'College'), ('CO', 'Company')], default='CO', max_length=2),
        ),
        migrations.AlterField(
            model_name='placementsession',
            name='application_deadline',
            field=models.DateField(help_text='Choose last date for students to apply. If no event is scheduled for now, choose an arbitrary future date.', null=True, verbose_name='Application Deadline'),
        ),
        migrations.AlterField(
            model_name='placementsession',
            name='ended',
            field=models.BooleanField(default=False, help_text='Setting it to true would mean that the students currently in the session are selected.', verbose_name='Has the placement session ended'),
        ),
    ]
