# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-25 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_auto_20170619_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 6, 25, 20, 43, 57, 403023)),
            preserve_default=False,
        ),
    ]
