# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 04:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_association_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementsession',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 26, 9, 52, 10, 331065)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementsession',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 6, 26, 9, 52, 13, 236988)),
            preserve_default=False,
        ),
    ]
