# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_auto_20160905_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementsession',
            name='last_modified_by',
            field=models.CharField(choices=[('C', 'College'), ('CO', 'Company')], default='C', max_length=2),
        ),
    ]
