# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 16:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_auto_20170626_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectioncriteria',
            name='years',
            field=models.CharField(blank=True, help_text='Eg. 1,2,3 (Without spaces anywhere)(In increasing order)', max_length=30, validators=[django.core.validators.RegexValidator('^([1-6](,[1-6])*)?$')], verbose_name='Which year students may apply'),
        ),
    ]
