# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dlrequest',
            old_name='requester',
            new_name='requesters',
        ),
        migrations.AddField(
            model_name='requester',
            name='downloaded_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 7, 26, 16, 59, 42, 595144, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
