# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20170726_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='requested_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
