# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20170728_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='downloaded_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='requested_on',
            field=models.DateTimeField(null=True),
        ),
    ]
