# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0006_auto_20170729_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zippedfile',
            name='zipped_file',
        ),
        migrations.AddField(
            model_name='zippedfile',
            name='filepath',
            field=models.CharField(default='/', max_length=1024),
            preserve_default=False,
        ),
    ]
