# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-29 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0007_auto_20170729_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zippedfile',
            name='filepath',
        ),
        migrations.AddField(
            model_name='zippedfile',
            name='zipped_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
