# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-29 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0008_auto_20170729_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zippedfile',
            name='zipped_file',
            field=models.FileField(blank=True, upload_to='compressed/'),
        ),
    ]
