# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 10:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Xth Percentage')),
                ('twelfth', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='XIIth Percentage')),
                ('graduation', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Graduation Percentage')),
                ('post_graduation', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Post Graduation Percentage')),
                ('doctorate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Doctorate Percentage')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128, verbose_name='First name')),
                ('lastname', models.CharField(blank=True, max_length=128, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='Gender')),
                ('dob', models.DateField(null=True, verbose_name='Date Of Birth')),
                ('photo', models.ImageField(blank=True, upload_to='student/photo', verbose_name='Photo')),
                ('phone_number', models.CharField(error_messages={'invalid_number': "Invalid IN Phone Number. Don't Prefix The Number With +91 or 0."}, help_text='Enter 10 Digit IN Mobile Number', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[7-9]\\d{9}$')], verbose_name='Mobile Number')),
                ('current_year', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('[1-6]')], verbose_name='Current Year')),
                ('is_sub_back', models.BooleanField(default=False, verbose_name='Any Subject Back(s)')),
                ('is_verified', models.NullBooleanField(default=None)),
                ('resume', models.FileField(blank=True, upload_to='student/resume')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='college.College')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='college.Programme')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='college.Stream')),
                ('verified_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(blank=True)),
                ('bitbucket', models.URLField(blank=True)),
                ('coding', models.TextField(blank=True, help_text='Eg. Code Chef, SPOJ, Code Forces, Hacker Earth', verbose_name='Miscellaneous Profile Links')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech', to='student.Student')),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='student.Student'),
        ),
    ]
