# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='is_verified',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='qualification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='doctorate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Doctorate Percentage'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='graduation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Graduation Percentage'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='post_graduation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Post Graduation Percentage'),
        ),
        migrations.AlterField(
            model_name='student',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles_verified', to=settings.AUTH_USER_MODEL),
        ),
    ]
