# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-14 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20160811_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, upload_to='student/resume', verbose_name='Resume'),
        ),
    ]
