# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20160814_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='doctorate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Doctorate Percentage'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='graduation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Graduation Percentage'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='post_graduation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Post Graduation Percentage'),
        ),
    ]
