# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 21:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20160815_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techprofile',
            name='coding',
        ),
        migrations.AddField(
            model_name='techprofile',
            name='codechef',
            field=models.CharField(blank=True, help_text='Please provide your Codechef username.', max_length=14, validators=[django.core.validators.RegexValidator('^[a-z]\\{1\\}[a-z0-9_]\\{3,13\\}$/')]),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='codeforces',
            field=models.CharField(blank=True, help_text='Please provide your Codeforces username.', max_length=24),
        ),
        migrations.AddField(
            model_name='techprofile',
            name='spoj',
            field=models.CharField(blank=True, help_text='Please provide your SPOJ username.', max_length=14),
        ),
    ]
