# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20160828_0057'),
        ('student', '0006_auto_20160827_1452'),
    ]

    operations = [
    ]
