# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 15:33
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_intern',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='salary_expected',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2 and above'), (4, '4 and above'), (6, '6 and above'), (8, '8 and above'), (10, '10 and above'), (12, '12 and above')], help_text="Caution: You won't be able to appear for companies offering salary less than the minimum you choose.", null=True, verbose_name='Minimum salary expected (Lakhs P.A.)'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='doctorate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('33'))], verbose_name='Doctorate Percentage'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='graduation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('33'))], verbose_name='Graduation Percentage'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='post_graduation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('33'))], verbose_name='Post Graduation Percentage'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='tenth',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('33'))], verbose_name='Xth Percentage'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='twelfth',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('33'))], verbose_name='XIIth Percentage'),
        ),
    ]
