# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20160831_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='salary_expected',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 and above'), (4, '4 and above'), (6, '6 and above'), (8, '8 and above'), (10, '10 and above'), (12, '12 and above')], help_text="Caution: You won't be able to appear for companies offering salary less than the minimum you choose. Also, you won't be able to change this again.", null=True, verbose_name='Minimum salary expected (Lakhs P.A.)'),
        ),
    ]
