# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20160831_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_barred',
            field=models.BooleanField(default=False, help_text='This will prevent the student from applying to companies for jobs as well as for internships.', verbose_name='Bar the student from applying to companies'),
        ),
    ]
