# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-12 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20170526_1548'),
        ('student', '0011_student_is_barred'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='applied_to',
            field=models.ManyToManyField(blank=True, related_name='applications', to='recruitment.PlacementSession'),
        ),
    ]
