# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_company', '0001_initial'),
        ('student', '0012_student_applied_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='applied_to',
            new_name='sessions_applied_to',
        ),
        migrations.AddField(
            model_name='student',
            name='dsessions_applied_to',
            field=models.ManyToManyField(blank=True, related_name='applications', to='dummy_company.DummySession'),
        ),
    ]
