# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20170613_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to=utils.get_hashed_filename, verbose_name='Photo'),
        ),
    ]
