# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20170613_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, upload_to=utils.get_hashed_filename, verbose_name='Resume'),
        ),
    ]
