# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 05:55
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20170613_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='tenth_cgpa',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Xth CGPA'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='tenth',
            field=models.DecimalField(decimal_places=2, default=Decimal('33'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('33'))], verbose_name='Xth Percentage'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='twelfth',
            field=models.DecimalField(decimal_places=2, default=Decimal('33'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('33'))], verbose_name='XIIth Percentage'),
        ),
    ]
