# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 20:50
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20170628_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='graduation',
            field=models.DecimalField(decimal_places=2, default=Decimal('33'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('33'))], verbose_name='Graduation Percentage'),
        ),
    ]
