# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20170629_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='subject_name',
            field=models.CharField(blank=True, help_text='You are mandated to enter the subject name exactly the same as is in marksheet.', max_length=128),
        ),
    ]
