# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20170629_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='marksheet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.SchoolMarksheet'),
        ),
    ]
