# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-29 20:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20170629_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='marks',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Marks out of 100'),
        ),
    ]
