# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-09 09:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20170630_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(error_messages={'invalid_number': "Invalid IN Phone Number. Don't Prefix The Number With +91 or 0."}, help_text='Enter 10 Digit IN Mobile Number', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', regex='^[7-9]\\d{9}$')], verbose_name='Mobile Number'),
        ),
    ]
