# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20170801_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('profile__username',)},
        ),
    ]
