# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-25 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20170809_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_graduated',
            field=models.BooleanField(default=False),
        ),
    ]
