# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 10:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='College name')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('\\d{3}')], verbose_name='College code')),
                ('address', models.TextField(blank=True, verbose_name='College address')),
                ('details', models.TextField(blank=True, verbose_name='Other details')),
                ('contact', models.TextField(blank=True, verbose_name='Contact details')),
                ('website', models.URLField(blank=True, verbose_name='College website')),
                ('photo', models.ImageField(blank=True, upload_to='college/photo', verbose_name='Photo')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Stream name')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('years', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)], default='4', max_length=1, verbose_name='Number of years')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Stream name')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('\\d{3}')], verbose_name='Stream code')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='college.Programme')),
            ],
        ),
        migrations.AddField(
            model_name='college',
            name='streams',
            field=models.ManyToManyField(related_name='colleges', to='college.Stream'),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together=set([('programme', 'code')]),
        ),
    ]
