# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company name')),
                ('corporate_code', models.CharField(max_length=11, unique=True, verbose_name='Company registration code')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('website', models.URLField(blank=True, verbose_name='Company website')),
                ('photo', models.ImageField(blank=True, upload_to='company/photo', verbose_name='Photo')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
