# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20170729_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, upload_to=utils.get_hashed_photo_name, verbose_name='Photo'),
        ),
    ]
