# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 10:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128, verbose_name='First name')),
                ('lastname', models.CharField(blank=True, max_length=128, verbose_name='Last name')),
                ('employee_id', models.CharField(blank=True, max_length=64, verbose_name='Employee ID')),
                ('phone_number', models.CharField(error_messages={'invalid_number': "Invalid IN Phone Number. Don't Prefix The Number With +91 or 0."}, help_text='Enter 10 Digit IN Mobile Number', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('[7-9]\\d{9}')], verbose_name='Mobile Number')),
                ('photo', models.ImageField(blank=True, upload_to='faculty/photo', verbose_name='Photo')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='college.College')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
