# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 20:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='firstname',
            field=models.CharField(max_length=128, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(error_messages={'invalid_number': "Invalid IN Phone Number. Don't Prefix The Number With +91 or 0."}, help_text='Enter 10 Digit IN Mobile Number', max_length=10, null=True, validators=[django.core.validators.RegexValidator('[7-9]\\d{9}')], verbose_name='Mobile Number'),
        ),
    ]
