# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20160811_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(blank=True, upload_to=utils.get_hashed_filename, verbose_name='Photo'),
        ),
    ]
