# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 10:58
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0004_auto_20161012_0002'),
        ('college', '0001_initial'),
        ('student', '0011_student_is_barred'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company name')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('website', models.URLField(blank=True, verbose_name='Company website')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dummy_companies', to='college.College')),
            ],
            options={
                'verbose_name_plural': 'Dummy Companies',
            },
        ),
        migrations.CreateModel(
            name='DummySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Internship'), ('J', 'Job')], default='J', max_length=1, verbose_name='Type')),
                ('salary', models.DecimalField(decimal_places=2, default=0, help_text='Salary to be offered in LPA.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salary (Lakhs P.A.)')),
                ('desc', models.TextField(blank=True, verbose_name="Placement details you'd want to mention")),
                ('status', models.CharField(blank=True, help_text="Mention this placement session's current status for shortlisted students' knowledge. Eg. Resume Submission, Final Round, HR Round, Personal Interview Round", max_length=256, verbose_name='Current status')),
                ('application_deadline', models.DateField(help_text='Choose last date for students to apply. If no event is scheduled for now, choose an arbitrary future date.', null=True, verbose_name='Application Deadline')),
                ('ended', models.BooleanField(default=False, help_text='Setting it to true would mean that the students currently in the session are selected.', verbose_name='Has the placement session ended')),
                ('dummy_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dummy_sessions', to='dummy_company.DummyCompany')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dummy_sessions', to='college.Programme')),
                ('selection_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dummy_sessions', to='recruitment.SelectionCriteria')),
                ('streams', models.ManyToManyField(help_text='Choose particular stream(s).', related_name='dummy_sessions', to='college.Stream')),
                ('students', models.ManyToManyField(blank=True, related_name='dummy_sessions', to='student.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dummycompany',
            unique_together=set([('name', 'college')]),
        ),
    ]
