# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 04:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummysession',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 26, 9, 52, 6, 277082)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dummysession',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 6, 26, 9, 52, 8, 603987)),
            preserve_default=False,
        ),
    ]
