# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-02 16:57
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_company', '0002_auto_20170626_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummysession',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Salary to be offered in LPA. If it's an internship, leave this as 0, and mention salary in placement details.", max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salary (Lakhs P.A.)'),
        ),
    ]
